yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthor.as_view(), name='author'),
    path('tech/', views.Technologies.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth import views
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordChangeDoneView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetView
from django.urls import path
from . import views


app_name = 'users'


urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        '<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'password_reset/complete/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from core.models import CreateModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200, null=False,
        verbose_name="Название сообщества",
    )
    slug = models.SlugField(
        unique=True,
        verbose_name="url адрес сообщества",
    )
    description = models.TextField(
        max_length=600,
        verbose_name="Описание сообщества",
    )

    def __str__(self) -> str:
        return self.title


class Post(CreateModel):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        related_name='posts',
        help_text='Выберите группу',
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']


class Comment(CreateModel):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField(
        'Текст',
        help_text='Текст нового комментария',
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name="follower",
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        related_name="following",
        on_delete=models.CASCADE
    )

yatube/posts/forms.py
from django import forms
from posts.models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Группа',
            'image': 'Картинка',
        }
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
            'image': 'Можете добавить картинку',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect, render


from .forms import PostForm, CommentForm
from .models import Post, Group, User, Follow
from django.contrib.auth.decorators import login_required


def get_page_pagination(queryset, request):
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return {
        'page_obj': page_obj,
    }


def index(request):
    context = get_page_pagination(Post.objects.all(), request)
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    context = {
        'group': group,
    }
    context.update(get_page_pagination(group.posts.all(), request))
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    template_name = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    user_posts = post_list.count()
    following = author.following.all()
    context = {
        'author': author,
        'user_posts': user_posts,
        'following': following,
    }
    context.update(get_page_pagination(author.posts.all(), request))
    return render(request, template_name, context)


def post_detail(request, post_id):
    template_name = 'posts/post_detail.html'
    full_post = get_object_or_404(Post, id=post_id)
    count_posts = full_post.author.posts.count()
    comment_form = CommentForm(request.POST or None)
    comments = full_post.comments.all()
    context = {
        'full_post': full_post,
        'count_posts': count_posts,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, template_name, context)


@login_required
def post_create(request):
    template_name = 'posts/create_post.html'
    if request.method == 'POST':
        form = PostForm(
            request.POST,
            files=request.FILES
        )
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', username=post.author)
        return render(request, template_name, {'form': form})
    form = PostForm()
    return render(request, template_name, {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if request.user != post.author:
        return redirect(
            'posts:post_detail',
            post_id=post_id,
        )
    if form.is_valid():
        form.save()
        return redirect(
            'posts:post_detail',
            post_id=post_id,
        )
    return render(
        request,
        'posts/create_post.html',
        {'form': form, 'post': post, 'is_edit': True}
    )


@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, id=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    context = get_page_pagination(post_list.all(), request)
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    follow = get_object_or_404(User, username=username)
    already_following = Follow.objects.filter(
        user=request.user,
        author=follow
    ).exists()
    if request.user != follow and not already_following:
        Follow.objects.get_or_create(user=request.user, author=follow)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    following = get_object_or_404(User, username=username)
    follower = get_object_or_404(Follow, author=following, user=request.user)
    follower.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
<html lang="ru">

  {% block title %}
    {% if not is_edit %}
      Новый пост
    {% else %}
      Редактировать пост
    {% endif %}
  {% endblock %}

  {% block content %}
  {% load user_filters %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
              {% if is_edit %}
                Редактировать пост 
              {% else %}       
                Новый пост
              {% endif %}             
              </div>
              <div class="card-body">
                {% for errors in form.errors %}
                  <div class="alert alert-danger" role="alert">
                    {{ error|escape }}
                  </div>
                {% endfor %}
       
                  <form method="post" enctype="multipart/form-data"
                    {% if is_edit %}
                      action="{% url 'posts:post_edit' post.pk %}"
                      {% csrf_token %}
                    {% else %}
                      action="{% url 'posts:post_create' %}">
                    {% endif %}
                  {% csrf_token %}
                    
                {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{field.id_for_label}}">
                      {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>    
                  {{ field|addclass:'form-control' }}
                    <small id="{{field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe}}
                    </small>
                </div>
                {% endfor %}          
                    <div class="d-flex justify-content-end">
                      <button type="submit" class="btn btn-primary">
                        {% if is_edit %}
                          Сохранить  
                        {% else %}
                          Добавить
                        {% endif %}
                      </button> 
                    </div>
                  </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  {% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Последние обновления избранных авторов{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}  
  {% include 'posts/includes/post_list.html' %}
  {% if post.group.slug %}
    <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
  {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html'%}
{% block title %} Записи сообщества {{group.title}}{% endblock %}
{% block header %}<h1>{{ group.title}}</h1>{% endblock %}
{% block content %}
{% load thumbnail %}

  <p>{{ group.description}}</p>
  {% for post in page_obj%}
  <ul>
    <li>
      Автор: {{ post.author.get_username }}
      <a href="{% url 'posts:profile' post.author.get_username %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height}}">
  {% endthumbnail %}
  <p>{{ post.text|linebreaksbr}}</p>
  <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block header %}<h1>Последние посты</h1>{% endblock %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content%}
{% load cache %}
{% cache 20 index_page %}
{% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
  {% include 'posts/includes/post_list.html' %}
    {% if post.group.slug %}<a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>{% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html'%}
{% block title %}Пост {{full_post.text|truncatechars:30}}{% endblock%}
{% load thumbnail %}
  {% block content %}
  {% load user_filters %}    
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ full_post.pub_date|date:"d E Y" }} 
            </li>
            {% if full_post.group.slug %}   
              <li class="list-group-item">
                Группа: {{ full_post.group.title }}
                <a href="{% url 'posts:group' full_post.group.slug %}">
                  все записи группы
                </a>
              </li>
            {% endif %}
              <li class="list-group-item">
                Автор: {{ full_post.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ count_posts }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' full_post.author.get_username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail full_post.image "960x339" crop="center" upscale=True as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height}}">
          {% endthumbnail %}
          <p>
           {{ full_post.text|linebreaksbr }} 
          </p>
          {% if user == full_post.author %}
          <a class="btn btn-sm btn-info" href="{% url 'posts:post_edit' full_post.id %}" role="button">
            Редактировать
          </a>
          {% endif %}
          {% if full_post.comments.exists %}
          <div>
            Комментариев: {{ full_post.comments.count }}
          </div>
          {% if user.is_authenticated %}
            <div class="card my-4">
              <h5 class="card-header">Добавить комментарий:</h5>
              <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' full_post.id %}">
                  {% csrf_token %}    
                  <div class="form-group mb-2">
                    {{ comment_form.text|addclass:"form-control" }}
                  </div>
                  <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
              </div>
            </div>
          {% else %}
          <a href="{% url 'users:login' %}"> Войдите </a>
          <a> или </a>
            <a href="{% url 'users:signup' %}">
              зарегистрируйтесь, чтобы оставлять комментарии!
            </a>
          {% endif %}
        
            <div class="col-md-9">
              {% include 'posts/includes/comments.html' %}
            </div>
            
        </article>
          </div>
        </div>
      {% endif %} 
    </main>
  {% endblock content %}
</html>

yatube/templates/posts/profile.html
{% extends 'base.html'%}
{% load thumbnail %}
{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}
  {% block content %}      
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ user_posts }} </h3> 
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
        {% endif %}  
        <article>
        {% for page_data in page_obj%}
          <ul>
            <li>
              Автор: {{ author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ page_data.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail page_data.image "960x339" crop="center" upscale=True as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height}}">
          {% endthumbnail %}
          <p>
          {{ page_data.text|linebreaksbr }}
          </p>
          <a href="{% url 'posts:post_detail' page_data.pk %}">подробная информация </a>
        </article>
        {% if page_data.group.slug %}       
        <a href="{% url 'posts:group' page_data.group.slug %}">все записи группы</a>
        {% endif %}       
        <hr>
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% if page_obj.has_other_pages %}
        {% include 'posts/includes/paginator.html'%}
        {% endif %}
      </div>
  {% endblock content %}
</html>